### ISSUE TITLE
Crash on game launch

### ISSUE THREAD

**Issue by TurboGurra** [atsb/NuBuildGDX#1] opened 2023-07-22 08:53 UTC
Program just exits when trying to launch a game, error log states that it failed to write a core dump: [hs_err_pid5584.log](https://github.com/atsb/NuBuildGDX/files/12136031/hs_err_pid5584.log)
This occurs when starting the game with the Polymost renderer selected.

**Comment by atsb** [comment] 2023-07-23 15:20
Thanks, very strange.  I’m on W11 for this and it is ok.  I’ll take a look

**Comment by Patrxgt** [comment] 2023-08-06 00:39
Same happens to me on Windows 10. I'm using Nvidia GPU and AMD Ryzen CPU.

**Comment by atsb** [comment] 2023-08-06 21:05
Looks like it is due to the app icon from what I can see, very weird.  I'll do some experiments on my other systems and see if I can reproduce this

**Comment by atsb** [comment] 2023-09-19 12:53
I've done a few things locally and will be looking into this tonight on my Linux machine especially

**Comment by atsb** [comment] 2024-09-22 05:55
This should be fixed now

**Comment by atsb** [comment] 2024-10-08 19:25
Fixed in 1.19.0

**Closed as completed by atsb** 2024-10-08 19:25 UTC
